# Generated by Django 5.1 on 2025-01-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_notificationstaffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='date',
            field=models.DateField(max_length=60),
        ),
    ]
