# Generated by Django 5.1 on 2025-01-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_leavereportstaff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
