# Generated by Django 5.1 on 2025-01-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_notificationstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
