# Generated by Django 5.1 on 2025-01-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_feepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeePayment',
        ),
    ]
